$e = $default_engine
$e.scene_bottom_left = Vector[0.0, 0.0]
$e.scene_top_right = Vector[-12.8, -8.0]
$e.scene_walls_changed
$r = RectangleThin48.new; $e.toys << $r; $r.move(Vector[6.4, 0.101]); $blk = $r.limbs.to_a.first
$e.run_steps(120)
$t = U6Bluebear.new; $e.toys << $t; $t.move(Vector[6.5, 3.4])
$ls = $t.limbs.to_a
$e.run_steps(10)
puts format("O010 %+.9e %+.9e %+.9e", 10, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O020 %+.9e %+.9e %+.9e", 20, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O030 %+.9e %+.9e %+.9e", 30, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O040 %+.9e %+.9e %+.9e", 40, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O050 %+.9e %+.9e %+.9e", 50, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O060 %+.9e %+.9e %+.9e", 60, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O070 %+.9e %+.9e %+.9e", 70, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O080 %+.9e %+.9e %+.9e", 80, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O090 %+.9e %+.9e %+.9e", 90, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O100 %+.9e %+.9e %+.9e", 100, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O110 %+.9e %+.9e %+.9e", 110, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O120 %+.9e %+.9e %+.9e", 120, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O130 %+.9e %+.9e %+.9e", 130, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O140 %+.9e %+.9e %+.9e", 140, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O150 %+.9e %+.9e %+.9e", 150, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O160 %+.9e %+.9e %+.9e", 160, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O170 %+.9e %+.9e %+.9e", 170, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O180 %+.9e %+.9e %+.9e", 180, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O190 %+.9e %+.9e %+.9e", 190, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O200 %+.9e %+.9e %+.9e", 200, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O210 %+.9e %+.9e %+.9e", 210, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O220 %+.9e %+.9e %+.9e", 220, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O230 %+.9e %+.9e %+.9e", 230, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O240 %+.9e %+.9e %+.9e", 240, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O250 %+.9e %+.9e %+.9e", 250, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O260 %+.9e %+.9e %+.9e", 260, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O270 %+.9e %+.9e %+.9e", 270, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O280 %+.9e %+.9e %+.9e", 280, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O290 %+.9e %+.9e %+.9e", 290, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O300 %+.9e %+.9e %+.9e", 300, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O310 %+.9e %+.9e %+.9e", 310, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O320 %+.9e %+.9e %+.9e", 320, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O330 %+.9e %+.9e %+.9e", 330, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O340 %+.9e %+.9e %+.9e", 340, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O350 %+.9e %+.9e %+.9e", 350, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O360 %+.9e %+.9e %+.9e", 360, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O370 %+.9e %+.9e %+.9e", 370, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O380 %+.9e %+.9e %+.9e", 380, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O390 %+.9e %+.9e %+.9e", 390, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O400 %+.9e %+.9e %+.9e", 400, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O410 %+.9e %+.9e %+.9e", 410, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
$e.run_steps(10)
puts format("O420 %+.9e %+.9e %+.9e", 420, $blk.position.y, $blk.orientation, $ls.map{|l| l.position.y}.min)
