#!/usr/bin/env python3
"""Generate src/ruby_api.inc from private/ruby_api_contract.json (internal;
intermediate).

Emits X-macro rows for the 21 engine classes / 332 method bindings the
Toybox binary exposes to Ruby (private/RUBY_API_CONTRACT.md). rubyhost.c
registers every row as a variadic stub first, then overrides the ones it
really implements; that way framework load-time aliases (e.g.
`alias :internal_render :render`) always resolve.

Class list and hierarchy are fixed here (from the RE artifacts above):
the 10 runtime SoupCollection template instances are folded into one
SoupNodeCollection base plus the 9 named container subclasses the framework
reopens.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CONTRACT = os.path.join(HERE, "..", "private", "ruby_api_contract.json")
OUT = os.path.join(HERE, "..", "src", "ruby_api.inc")

# (class, superclass); Object/Exception = Ruby builtins. Order = definition order.
CLASSES = [
    ("SoupNode", "Object"),
    ("SoupNodeCollection", "SoupNode"),
    ("ToyContainer", "SoupNodeCollection"),
    ("LimbContainer", "SoupNodeCollection"),
    ("JointContainer", "SoupNodeCollection"),
    ("RotationalJointContainer", "SoupNodeCollection"),
    ("SpriteContainer", "SoupNodeCollection"),
    ("SoundContainer", "SoupNodeCollection"),
    ("ShapeContainer", "SoupNodeCollection"),
    ("RotationalMotorContainer", "SoupNodeCollection"),
    ("LinearMotorContainer", "SoupNodeCollection"),
    ("Toy", "SoupNode"),
    ("IconToy", "Toy"),
    ("ToyManager", "SoupNode"),
    ("Limb", "SoupNode"),
    ("Joint", "SoupNode"),
    ("RotationalJoint", "SoupNode"),
    ("RotationalMotor", "SoupNode"),
    ("LinearMotor", "SoupNode"),
    ("Sprite", "SoupNode"),
    ("Canvas", "Sprite"),
    ("Shape", "SoupNode"),
    ("Sound", "SoupNode"),
    ("Souptoys", "Object"),
    ("RCore", "Object"),
    ("REngine", "Object"),
    ("RInput", "Object"),
    ("RVideoFile", "Object"),
    ("Toybox", "Object"),
    ("AlreadyRunningException", "Exception"),
]

ENGINE_CLASSES = {c for c, _ in CLASSES}


def main():
    with open(CONTRACT) as f:
        bindings = json.load(f)["bindings"]

    # (class, method, kind) -> argc; template instances folded into one
    rows = {}
    for b in bindings:
        cls = b["class"]
        if cls.startswith("SoupCollection@"):
            cls = "SoupNodeCollection"
        elif cls not in ENGINE_CLASSES:
            continue
        kind = b["kind"]
        if kind not in ("method", "singleton_method", "private_method"):
            continue
        # never stub out Class#new: a nil-returning stub would break
        # rb_class_new_instance for every collection class
        if kind == "singleton_method" and b["method"] == "new":
            continue
        argc = b["argc"]
        if argc > 16:  # 2^64-1 encodes C variadic (*args)
            argc = -1
        rows[(cls, b["method"], kind)] = argc

    with open(OUT, "w") as f:
        f.write("// generated by tools/gen-ruby-api.py; do not edit.\n")
        f.write("// engine classes + method stubs, extracted from "
                "Toybox.exe's rb_define_* calls.\n")
        for cls, sup in CLASSES:
            f.write(f"RBA_CLASS({cls}, {sup})\n")
        n = 0
        for cls, _ in CLASSES:
            for (c, m, kind), argc in sorted(rows.items()):
                if c != cls:
                    continue
                macro = {"method": "RBA_METHOD",
                         "singleton_method": "RBA_SMETHOD",
                         "private_method": "RBA_PMETHOD"}[kind]
                f.write(f'{macro}({cls}, "{m}", {argc})\n')
                n += 1
        print(f"{OUT}: {len(CLASSES)} classes, {n} method rows")


if __name__ == "__main__":
    sys.exit(main())
